### PR TITLE
Expand reporting for errors that can occur when sending deploys/transactions to casper-networks.

### LINKED ISSUE #286: Bug report: Transaction rejection error messages in sidecar.
The error messages in the sidecar related to the rejection of transaction from the node implies that execution of invalid transactions is being attempted, and failing. These should be reworked, in conjunction with changes to the error messages reported over the binary to facilitate more ergonomic use.

### PR DESCRIPTION
**Pull request by zacshowa**
This PR expands error reporting for RPC requests that send `Deploy`s or `Transaction`s to casper networks. 
This supports the work done to the binary port [here](https://github.com/casper-network/casper-node/pull/4683)

### CODE REVIEW

File: rpc_sidecar/src/node_client.rs [hunk 1]
```diff
@@ -323,8 +554,8 @@ impl Error {
                 | ErrorCode::InvalidTransactionUnableToCalculateGasCost
                 | ErrorCode::InvalidTransactionPricingMode
                 | ErrorCode::InvalidTransactionUnspecified
-                | ErrorCode::InvalidTransactionOrDeployUnspecified,
-            ) => Self::InvalidTransaction, // TODO: map transaction errors to proper variants
+                | ErrorCode::InvalidTransactionOrDeployUnspecified),
+            ) => Self::InvalidTransaction(InvalidTransactionOrDeploy::from(err)), // TODO: map transaction errors to proper variants
```
Comment (jacek-casper) [inline rpc_sidecar/src/node_client.rs]:
```suggestion
            ) => Self::InvalidTransaction(InvalidTransactionOrDeploy::from(err)),
```
you can remove the todo now

**Comment by jacek-casper** [comment]
lgtm, let's just remove the TODO

**Review by jacek-casper — APPROVED** [review]
